//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace TicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardInfo
    {
        public int ID { get; set; }
        [Display(Name = "User ID")]
        public int UserID { get; set; }
        [Display(Name = "Card Number")]
        public string CardNumber { get; set; }
        public int ProviderID { get; set; }
    
        public virtual CardProvider CardProvider { get; set; }
        public virtual RegisteredUser RegisteredUser { get; set; }
    }
}
